-- Sync the locations/tide_stations tables with the bundled guide data.
--
-- Generated by scripts/gen-location-seed.mjs — do not hand-edit; regenerate.
--
-- Why this exists: refresh-conditions polls whatever stations the locations
-- table names, and readConditions() refuses to return a snapshot for a slug
-- that is not in it. The guide expanded from 15 spots to 25 and the table did
-- not follow, so ten spots — St. Pete Pier, Skyway North, both Fort De Soto
-- piers, Egmont Key, Weedon Island, Pass-a-Grille, Bunces Pass, New Pass and
-- South Lido — had no live tide at all, and six NOAA stations were never
-- polled. Nothing errored; the cards just read "updated unknown".
--
-- Idempotent: safe to re-run, and safe to run against the current 15 rows.

begin;

-- 15 NOAA CO-OPS stations
insert into public.tide_stations (id, name, url) values ('8726273', 'NOAA Desoto Point 8726273', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726273')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726249', 'NOAA Palma Sola Bay North 8726249', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726249')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726247', 'NOAA Bradenton, Manatee River 8726247', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726247')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726217', 'NOAA Cortez 8726217', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726217')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726282', 'NOAA Anna Maria, City Pier 8726282', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726282')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726233', 'NOAA Palma Sola Bay South 8726233', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726233')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8725747', 'NOAA Englewood, Lemon Bay 8725747', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8725747')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8725667', 'NOAA Placida, Gasparilla Sound 8725667', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8725667')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8725577', 'NOAA Port Boca Grande, Charlotte Harbor 8725577', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8725577')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726520', 'NOAA St. Petersburg, Tampa Bay 8726520', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726520')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726428', 'NOAA Tierra Verde 8726428', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726428')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726364', 'NOAA Mullet Key, Tampa Bay 8726364', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726364')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726347', 'NOAA Egmont Key, Tampa Bay 8726347', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726347')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726089', 'NOAA Longboat Key, Sarasota Bay 8726089', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726089')
  on conflict (id) do update set name = excluded.name, url = excluded.url;
insert into public.tide_stations (id, name, url) values ('8726034', 'NOAA Siesta Key, Big Sarasota Pass 8726034', 'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8726034')
  on conflict (id) do update set name = excluded.name, url = excluded.url;

-- 25 locations
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('emerson-point', 'Emerson Point / Snead Island', 'Bradenton', 27.5208, -82.644, 'shore, kayak', ARRAY['grass','oyster','mangrove']::text[], '8726273')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('palma-sola-bay', 'Palma Sola Bay', 'Bradenton', 27.4962, -82.6684, 'shore, wade', ARRAY['grass','potholes']::text[], '8726249')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('green-bridge', 'Green Bridge', 'Bradenton', 27.5003, -82.5705, 'shore, pier', ARRAY['pilings','channel','lights']::text[], '8726247')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('bradenton-riverwalk', 'Bradenton Riverwalk', 'Bradenton', 27.4989, -82.5688, 'shore', ARRAY['seawall','docks']::text[], '8726247')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('bridge-street-pier', 'Bridge Street / Bradenton Beach', 'Anna Maria', 27.4677, -82.698, 'pier, shore', ARRAY['pilings','current']::text[], '8726217')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('longboat-pass', 'Longboat Pass', 'Anna Maria', 27.4414, -82.6916, 'shore, boat', ARRAY['deep pass','bridge']::text[], '8726217')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('coquina-beach', 'Coquina Beach', 'Anna Maria', 27.4438, -82.691, 'shore', ARRAY['surf trough','pass edge']::text[], '8726217')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('bean-point', 'Bean Point', 'Anna Maria', 27.5387, -82.7443, 'shore', ARRAY['point','surf cuts']::text[], '8726282')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('cortez-bridge', 'Cortez Bridge', 'Bradenton', 27.4669, -82.6883, 'shore, bridge', ARRAY['bridge','docks']::text[], '8726217')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('south-palma-sola-flats', 'South Palma Sola Flats', 'Bradenton', 27.4798, -82.6758, 'kayak, wade', ARRAY['grass','potholes']::text[], '8726233')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('stump-pass', 'Stump Pass', 'Englewood', 26.9111, -82.3529, 'shore, kayak', ARRAY['pass','surf','mangrove']::text[], '8725747')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('englewood-beach', 'Englewood Beach', 'Englewood', 26.9258, -82.3612, 'shore', ARRAY['surf trough','cuts']::text[], '8725747')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('lemon-bay-mangroves', 'Lemon Bay Mangroves', 'Englewood', 26.9562, -82.3328, 'kayak, boat', ARRAY['points','grass','drains']::text[], '8725747')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('placida-gasparilla-sound', 'Placida / Gasparilla Sound', 'Placida', 26.833, -82.2675, 'boat, kayak', ARRAY['mangrove','flats','docks']::text[], '8725667')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('boca-grande-pass', 'Boca Grande Pass', 'Boca Grande', 26.7208, -82.2694, 'boat', ARRAY['major pass','deep current']::text[], '8725577')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('weedon-island', 'Weedon Island Preserve', 'St. Petersburg', 27.8438, -82.6113, 'pier, kayak, shore', ARRAY['mangrove','oyster','grass','drains']::text[], '8726520')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('st-pete-pier', 'St. Pete Pier', 'St. Petersburg', 27.7737, -82.6228, 'pier, shore', ARRAY['pier pilings','seawall','lights']::text[], '8726520')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('pass-a-grille-jetty', 'Pass-a-Grille Jetty', 'St. Pete Beach', 27.681, -82.7405, 'shore, wade', ARRAY['jetty point','pass','surf trough','sandbar cuts']::text[], '8726428')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('skyway-pier-north', 'Skyway Fishing Pier — North', 'Skyway', 27.6363, -82.668, 'pier', ARRAY['bridge pilings','deep channel','lights','current seam']::text[], '8726364')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('egmont-key', 'Egmont Key', 'Skyway', 27.6008, -82.7607, 'boat, shore', ARRAY['deep channel','sandbar cuts','grass','surf trough']::text[], '8726347')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('fort-de-soto-gulf-pier', 'Fort De Soto Gulf Pier', 'Fort De Soto', 27.6135, -82.7383, 'pier', ARRAY['pier pilings','deep channel','surf trough']::text[], '8726347')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('fort-de-soto-bay-pier', 'Fort De Soto Bay Pier', 'Fort De Soto', 27.616, -82.726, 'pier', ARRAY['pier pilings','grass','sand potholes']::text[], '8726364')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('bunces-pass-shell-key', 'Bunces Pass / Shell Key', 'Fort De Soto', 27.6501, -82.7392, 'kayak, boat, wade', ARRAY['pass','sandbar cuts','grass','sand potholes','mangrove']::text[], '8726428')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('new-pass-ken-thompson', 'New Pass / Ken Thompson Park', 'Sarasota', 27.3351, -82.575, 'shore, kayak, boat', ARRAY['pass','seawall','docks','grass']::text[], '8726089')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;
insert into public.locations (slug, name, region, lat, lng, access, structures, tide_station_id)
  values ('south-lido-park', 'South Lido Park / Big Sarasota Pass', 'Sarasota', 27.3036, -82.5678, 'shore, kayak, wade', ARRAY['pass','grass','mangrove','surf trough','sand potholes']::text[], '8726034')
  on conflict (slug) do update set
    name = excluded.name, region = excluded.region, lat = excluded.lat, lng = excluded.lng,
    access = excluded.access, structures = excluded.structures,
    tide_station_id = excluded.tide_station_id;

commit;
